### PR TITLE
Add CMake build for DIAMOND

### PR DESCRIPTION
**Pull request by yesimon**
Wanted to simplify make+install over a configure-less bare Makefile for compatibility with homebrew. Let me know if you have any questions.

### CODE REVIEW

**Comment by bbuchfink** [comment]
Hi Simon,

what's the problem with the current makefile setup?

Benjamin

2015-03-26 17:11 GMT+01:00 Simon Ye <notifications@github.com>:

**Comment by yesimon** [comment]
The primary motivation was to make a homebrew formula that can install diamond. Since homebrew relies on setting environment variables like $CC, $CPPFLAGS etc to do ```-I``` and ```-L``` flags for includes and linking, make clobbers them in a Makefile where these variables are set. Without having a ./configure step these kinds of things are hard. I did try using ```CPPFLAGS?=``` variable assignments in the Makefile in another branch which would work, but I took a look at the build which is fairly easy for cmake and can also handle finding system boost libraries and cross platform so I figured why not.

**Comment by bbuchfink** [comment]
A lot of people don't have cmake installed which is why I'd rather not use
it. And on servers/clusters its not always easy to get an admin to install
something for you either...

2015-03-26 17:33 GMT+01:00 Simon Ye <notifications@github.com>:

**Comment by yesimon** [comment]
Well cmake is pretty common on servers/clusters and used by projects like OpenCV, MySQL, VTK etc  and users can install a local version of it. 

How about having both a CMakeLists as well as a regular Makefile?

**Comment by bbuchfink** [comment]
Yes that's a good idea.

**Comment by yesimon** [comment]
I've fixed the PR.

**Comment by bbuchfink** [comment]
done

**Pull request merged**
